spring:
  application:
    name: restapi

  datasource:
    url: jdbc:mysql://localhost:3306/expensetransactions
    username: root
    password: 12345

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  servlet:
    context-path: /api/v1